elcodi_configuration:
    mapping:
        configuration:
            class: QBH\StoreConfigurationBundle\Entity\Configuration
            mapping_file: @StoreConfigurationBundle\Resources/config/doctrine/Configuration.orm.yml

elcodi_currency:
    mapping:
        currency:
            class: QBH\StoreCurrencyBundle\Entity\Currency
            mapping_file: @StoreCurrencyBundle/Resources/config/doctrine/Currency.orm.yml

elcodi_product:
    mapping:
        category:
            class: QBH\StoreProductBundle\Entity\Category
            mapping_file: @StoreProductBundle/Resources/config/doctrine/Category.orm.yml
        manufacturer:
            class: QBH\StoreProductBundle\Entity\Manufacturer
            mapping_file: @StoreProductBundle/Resources/config/doctrine/Manufacturer.orm.yml
        product:
            class: QBH\StoreProductBundle\Entity\Product
            mapping_file: @StoreProductBundle/Resources/config/doctrine/Product.orm.yml